### ISSUE TITLE
 Could you make it easier to use?

### ISSUE THREAD

**Issue by Chung-Chase52** [dylan-kwon/android-paging-modifier#4]
I would appreciate it if it only required implementation.

Credentials are too inconvenient!

**Comment by dylan-kwon** [comment]
It's now available with `implementation("io.github.dylan-kwon:paging-modifier-core:$version")`

I'll update the documentation shortly and then close this issue.

**Comment by dylan-kwon** [comment]
[Updated installation guide](https://github.com/dylan-kwon/android-paging-modifier?tab=readme-ov-file#installation).
